### ISSUE TITLE
Aggregation selection query is impractical in grafana

### ISSUE THREAD

**Issue by tve** [timescale/examples#12]
Thanks for the https://github.com/timescale/examples/blob/master/grafana-guide/advanced-tips/webinar-demo-queries.sql example for "Auto-changing aggregate queried". The union all query works, but it's totally impractical in grafana as far as I"m concerned. I have over hundred graphs that I want to switch over to using a set of aggregation tables and it's just impractical and unmaintainable to change all of them from relatively simple queries built using the grafana query UI to the big query shown in this demo.

I've been looking for a maintainable alternative and two approaches that have not worked, but maybe I've overlooked a trick is to use a plpgsql function to return the table name to query (can't do that) and to use a function to return the table to query using `return query execute`, which doesn't work either (the return table is materialized).

SO far the best I've come up with is the following, which is based on the union all query in the demo:
```
CREATE OR REPLACE VIEW meas AS
  SELECT *, 0 AS lvl FROM measurements_raw
  UNION ALL
  SELECT *, 1 AS lvl FROM measurements_avg_10m
;
```
and then
```
/* return the aggregation level based on the $__interval_ms between points */
CREATE OR REPLACE FUNCTION ival2lvl(iv integer)
  RETURNS smallint
LANGUAGE plpgsql AS
$func$
BEGIN
  IF iv >= 600*1000 THEN RETURN 1; /* 10 minute threshold */
  ELSE RETURN 0;
  END IF;
END
$func$;
```
to be used by adding a `WHERE lvl = ival2lvl($__interval_ms)` into the grafana queries. So far the resulting query plans are not always that great, though. It works for simple queries but fails if there are a bunch of where clauses.

Another option is to add lvl as a real column into the data table and partition on it. I think what really needs to happen, though, is to add a table-selection function into grafana itself.

**Comment by tve** [comment]
Quick update: I managed to make the above work reasonably by marking the ival2lvl function as immutable. That makes a significant query plan improvement. If we could get a function like that integrated into grafana the query plans would be even better.

**Comment by jonatas** [comment]
Smart hack @tve! maybe it worth submitting a PR to grafana directly?

**Comment by tve** [comment]
Well, the real question here is "worth it?"
It's already a lot of work to just get a thumbs-up/down on whether a PR might even be considered...

**Comment by jonatas** [comment]
@tve I'm sorry if it doesn't worth it.


If you have a hundred queries, you can probably hack the statements through the AST to get there. Here is a good source that maybe can help: https://github.com/pganalyze/pg_query#modifying-a-parsed-query-and-turning-it-into-sql-again

@avthars originally wrote the script and probably it was for learning purposes. Maybe someone can optimize the queries in some how, I'd suggest you to join the community slack and also you can get different opinions on that.
